version: "3"

services:
  mariadb:
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - wp
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_HOST
        - MYSQL_DATABASE
        - WP_ADMIN
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASSWORD
        - WP_USER_EMAIL
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_DATABASE
      - WP_ADMIN
      - WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PASSWORD
      - WP_USER_EMAIL
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html/
    networks:
      - wp
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
    networks:
      - wp
    depends_on:
      - wordpress
    restart: always

networks:
  wp:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/$USER/data/wordpress
  database:
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: /home/$USER/data/database
